{% set version = "0.4.1" %}

package:
  name: robotframework-stacktrace
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotframework-stacktrace/robotframework-stacktrace-{{ version }}.tar.gz
  sha256: e96cb36e7e9ab55104c1f7d3606249a109e0a4c3bb6a0e294bff07d54ee6f6a5

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - robotframework >=3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - RobotStackTracer
  commands:
    - pip check

about:
  home: https://github.com/MarketSquare/robotframework-stacktrace
  summary: A listener that prints a Stack Trace to console to faster find the code section where the failure appears.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
